# -*- coding: utf-8 -*-
"""model_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11Vby2D-dgCLRfZNVn22Dh_WazJRMO3NU
"""

import os
os.environ["WANDB_DISABLED"] = "true"
os.environ["WANDB_MODE"] = "disabled"
os.environ["WANDB_SILENT"] = "true"

!pip install -q transformers datasets accelerate scikit-learn torch plotly seaborn

import torch
print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

import torch
print(torch.cuda.is_available())
print(torch.cuda.get_device_name(0) if torch.cuda.is_available() else "No GPU")

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("FinSenseAI_15000_balanced_noisy_dataset.csv")
print("Total rows:", len(df))
df.head()

from sklearn.preprocessing import LabelEncoder
import json

le = LabelEncoder()
df['label'] = le.fit_transform(df['category'])

category_map = {str(i): label for i, label in enumerate(le.classes_)}

with open("category_map.json", "w") as f:
    json.dump(category_map, f, indent=4)

df.head()

from sklearn.model_selection import train_test_split

train_df, test_df = train_test_split(
    df,
    test_size=0.10,
    random_state=42,
    stratify=df['label']
)

len(train_df), len(test_df)

from transformers import DistilBertTokenizerFast

tokenizer = DistilBertTokenizerFast.from_pretrained("distilbert-base-uncased")
MAX_LEN = 72

import torch

class TxDataset(torch.utils.data.Dataset):
    def __init__(self, texts, labels, tokenizer, max_length=72):
        self.texts = texts.tolist()
        self.labels = labels.tolist()
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        text = self.texts[idx]
        enc = self.tokenizer(
            text,
            padding="max_length",
            truncation=True,
            max_length=self.max_length,
            return_tensors="pt"
        )
        return {
            "input_ids": enc["input_ids"][0],
            "attention_mask": enc["attention_mask"][0],
            "labels": torch.tensor(self.labels[idx])
        }

train_dataset = TxDataset(train_df["text"], train_df["label"], tokenizer)
test_dataset = TxDataset(test_df["text"], test_df["label"], tokenizer)

from transformers import DistilBertForSequenceClassification
import numpy as np
from sklearn.metrics import accuracy_score, precision_recall_fscore_support

num_labels = df['label'].nunique()

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=num_labels
)

def compute_metrics(pred):
    labels = pred.label_ids
    preds = np.argmax(pred.predictions, axis=1)

    acc = accuracy_score(labels, preds)
    precision, recall, f1, _ = precision_recall_fscore_support(
        labels, preds, average='weighted', zero_division=0
    )
    return {"accuracy": acc, "precision": precision, "recall": recall, "f1": f1}

from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=3e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=64,
    num_train_epochs=3,
    weight_decay=0.01,
    logging_strategy="steps",
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
    fp16=torch.cuda.is_available(),   # GPU optimization
    report_to="none",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=test_dataset,
    compute_metrics=compute_metrics
)

trainer.train()

metrics = trainer.evaluate()
metrics

from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

pred_out = trainer.predict(test_dataset)
preds = np.argmax(pred_out.predictions, axis=1)
labels = test_df['label'].tolist()

print("\nClassification Report:\n")
print(classification_report(labels, preds, target_names=le.classes_))

cm = confusion_matrix(labels, preds)

plt.figure(figsize=(10,8))
sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=le.classes_,
    yticklabels=le.classes_
)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix")
plt.show()

model.save_pretrained("FinSenseAI_model")
tokenizer.save_pretrained("FinSenseAI_tokenizer")

!zip -r FinSenseAI_model.zip FinSenseAI_model >/dev/null
!zip -r FinSenseAI_tokenizer.zip FinSenseAI_tokenizer >/dev/null

from google.colab import files
files.download("FinSenseAI_model.zip")
files.download("category_map.json")

import json

with open("training_metrics.json", "w") as f:
    json.dump(metrics, f, indent=4)

from google.colab import files
files.download("training_metrics.json")